import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const router = useRouter();
  const [formData, setFormData] = useState({
    username: "",
    password: "",
  });

  const handleChange = (event: React.ChangeEvent<any>) => {
    const { name, value } = event.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };

  const handleSubmit = () => {
    if (formData.username === "admin" && formData.password === "123") {
      router.push("/admin/dashboard");
    } else if (
      formData.username === "employee" &&
      formData.password === "123"
    ) {
      router.push("/employee/dashboard");
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Health System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full flex flex-col items-center justify-center h-screen bg-slate-200 -pt-6">
        <p className="mb-4 text-slate-800 font-bold text-[30px]">
          Barangay Balucuc Health System
        </p>
        <div className=" w-[30%] bg-white mx-auto py-8 px-6 rounded-md shadow-xl">
          <div>
            <div className="mb-6">
              <label
                htmlFor="username"
                className="block mb-2 text-md font-normal text-[#525F7F] dark:text-gray-300"
              >
                Your username
              </label>
              <input
                onChange={handleChange}
                name="username"
                value={formData.username}
                className="bg-gray-50 border border-gray-300 text-gray-900 
              text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5
              dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400
                dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              />
            </div>
            <div className="mb-6">
              <label
                htmlFor="password"
                className="block mb-2 text-md font-normal text-[#525F7F] dark:text-gray-300"
              >
                Your password
              </label>
              <input
                onChange={handleChange}
                name="password"
                value={formData.password}
                type="password"
                className="bg-gray-50 border border-gray-300
            text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 
            block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400
              dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              />
            </div>
            <div className="w-full text-right">
              <button
                type="submit"
                className=" text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none
               focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 
                dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
                onClick={handleSubmit}
              >
                Login
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
